const mongoose = require('mongoose');
const requireUser = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

const Survey = mongoose.model('surveys');

module.exports = app => {
  // define an arrow function, immediately export it and
  // wired up in express app inside the top level index.js

  app.get('/api/surveys/thanks', (req, res) => {
    res.send('Thanks for voting!');
  });

  app.post('/api/surveys', requireUser, requireCredits, async (req, res) => {
    // you call middlewares by order
    const { title, subject, body, recipients } = req.body;

    const survey = new Survey({
      // instance in the memory
      title,
      subject,
      body,
      recipients: recipients.split(',').map(email => ({ email })),
      _user: req.user.id, // generated by mongoose
      dateSent: Date.now(),
    });

    // Great place to send an email!

    const mailer = new Mailer(survey, surveyTemplate(survey));
    try {
      await mailer.send();
      await survey.save();
      req.user.credits -= 1;
      const user = await req.user.save();

      res.send(user);
    } catch (err) {
      res.status(422).send(err);
    }
  });
};
