const _ = require('lodash');
const Path = require('path-parser').default;
const { URL } = require('url');
const mongoose = require('mongoose');
const requireUser = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

const Survey = mongoose.model('surveys');

module.exports = app => {
  // define an arrow function, immediately export it and
  // wired up in express app inside the top level index.js

  app.get('/api/surveys', requireUser, async (req, res) => {
    const surveys = await Survey.find({ _user: req.user.id }).select({
      recipients: false,
    });
    res.send(surveys);
  });

  app.get('/api/surveys/:surveyId/:choice', (req, res) => {
    res.send('Thanks for voting!');
  });

  app.post('/api/surveys/webhooks', (req, res) => {
    // all events in req.body
    const p = new Path('/api/surveys/:surveyId/:choice');
    _.chain(req.body)
      .map(({ email, url }) => {
        const match = p.test(new URL(url).pathname);
        if (match) {
          return {
            email,
            surveyId: match.surveyId,
            choice: match.choice,
          };
        }
      })
      .compact() // remove undefined values
      .uniqBy('email', 'surveyId')
      .each(({ surveyId, email, choice }) => {
        Survey.updateOne(
          {
            _id: surveyId,
            recipients: {
              $elemMatch: { email, responded: false },
            },
          },
          {
            // update with this one
            $inc: { [choice]: 1 }, // key interpolation
            $set: { 'recipients.$.responded': true }, // $ element from original query, appropriate recipient
            lastResponded: new Date(),
          }
        ).exec();
      })
      .value(); // return newly processed array

    res.send({});
  });

  app.post('/api/surveys', requireUser, requireCredits, async (req, res) => {
    // you call middlewares by order
    const { title, subject, body, recipients } = req.body;

    const survey = new Survey({
      // instance in the memory
      title,
      subject,
      body,
      recipients: recipients.split(',').map(email => ({ email })),
      _user: req.user.id, // generated by mongoose
      dateSent: Date.now(),
    });

    // Great place to send an email!

    const mailer = new Mailer(survey, surveyTemplate(survey));
    try {
      await mailer.send();
      await survey.save();
      req.user.credits -= 1;
      const user = await req.user.save();

      res.send(user);
    } catch (err) {
      res.status(422).send(err);
    }
  });
};
